INFO:transaction module:---processing  transaction related  queries---
INFO:transaction module:---uids---780
INFO:transaction module:config_meta.Session_userAccountId-40
INFO:transaction module:---session id-780
INFO:transaction module:inside deposit
INFO:payee_service:--- inside  transaction  service---
INFO:Classes.add_account_dao:---initializing Account info for user---
INFO:Classes.add_account_dao:Connection Established
INFO:Classes.add_account_dao:---fecthing account no on basis of account---
INFO:transaction module:---deposit related queries in process id--
INFO:payee_service:--- inside  transaction  service---
INFO:Classes.transation_dao:Connection Established
INFO:Classes.transation_dao:transaction_id :-None  user_id:-780  transaction_no:-1527399759
INFO:Classes.transation_dao:---deposit transaction is being initiated---
ERROR:Classes.transation_dao:Unable to insert records:-
Traceback (most recent call last):
  File "D:\PythonProc\Banking-app\src\Classes\transation_dao.py", line 41, in do_transaction_update
    VALUES ('%s', %.2f, '%s', '%s', '%s',%d)" % (transaction.transaction_type,transaction.amount,transaction.recipient_account_number,transaction.recipient_account_bank,transaction.transaction_no,transaction.user_id)
TypeError: must be real number, not str
INFO:transaction module:---transaction Failed---
INFO:user_login:---processing  user login---
INFO:Classes.user_details_dao:Connection Established
INFO:Classes.user_details_dao:---inside user Dao for login---
INFO:Classes.user_details_dao:select user_id,user_name,account_id from user_info where user_name='mishra92@gmail.com' and password= 'M1030513'
INFO:Classes.user_details_dao:(780, 'mishra92@gmail.com', 40)
INFO:user_login:db response:-780_mishra92@gmail.com_40
DEBUG:user_login:---user logged id in successfully
INFO:user_login:---userAccountId--40
INFO:user_login:---  cookie[accountId]--40
INFO:user_login:---config_meta.Session_userAccountId--40
INFO:account module:---processing account modules---
INFO:account module:querytype:-ACCOUNT_INFOuid:-780
INFO:root:account holder id:-40
INFO:Classes.user_Detail_services:---fetching account Details---
INFO:Classes.user_details_dao:Connection Established
INFO:Classes.add_account_dao:---initializing Account info for user---
INFO:Classes.add_account_dao:---fecting account  info---
INFO:Classes.add_account_dao:SELECT account_no,current_balance,bank_name,bank_branch,account_type from  account_info where account_id=40
DEBUG:account module:---Fetched account details successfully
INFO:transaction module:---processing  transaction related  queries---
INFO:transaction module:---uids---780
INFO:transaction module:config_meta.Session_userAccountId-40
INFO:transaction module:---session id-780
INFO:transaction module:inside deposit
INFO:payee_service:--- inside  transaction  service---
INFO:Classes.add_account_dao:---initializing Account info for user---
INFO:Classes.add_account_dao:Connection Established
INFO:Classes.add_account_dao:---fecthing account no on basis of account---
INFO:transaction module:---deposit related queries in process id--
INFO:payee_service:--- inside  transaction  service---
INFO:Classes.transation_dao:Connection Established
INFO:Classes.transation_dao:transaction_id :-None  user_id:-780  transaction_no:-1527400095
INFO:Classes.transation_dao:---deposit transaction is being initiated---
ERROR:Classes.transation_dao:Unable to insert records:-
Traceback (most recent call last):
  File "D:\PythonProc\Banking-app\src\Classes\transation_dao.py", line 41, in do_transaction_update
    VALUES ('%s', %.2f, '%s', '%s', '%s',%d)" % (transaction.transaction_type,transaction.amount,transaction.recipient_account_number,transaction.recipient_account_bank,transaction.transaction_no,int(transaction.user_id))
TypeError: must be real number, not str
INFO:transaction module:---transaction Failed---
